use wasmtime::component::bindgen;

bindgen!({
    path: "../pumpkin-plugin-wit/v0.2",
    world: "plugin",
    imports: {
        "pumpkin:plugin/command@0.2.0.[method]command-sender.has-permission": async | store | trappable,
        "pumpkin:plugin/datapack@0.2.0.[method]datapack-manager.disable-pack": async | store | trappable,
        "pumpkin:plugin/datapack@0.2.0.[method]datapack-manager.enable-pack": async | store | trappable,
        "pumpkin:plugin/datapack@0.2.0.[method]datapack-manager.execute-function": async | store | trappable,
        "pumpkin:plugin/datapack@0.2.0.[method]datapack-manager.reload": async | store | trappable,
        "pumpkin:plugin/ipc@0.2.0.send-ipc-message": async | store | trappable,
        "pumpkin:plugin/menu@0.2.0.open": async | store | trappable,
        "pumpkin:plugin/modded@0.2.0.open-menu": async | store | trappable,
        "pumpkin:plugin/player@0.2.0.[method]player.add-effect": async | store | trappable,
        "pumpkin:plugin/player@0.2.0.[method]player.add-experience-levels": async | store | trappable,
        "pumpkin:plugin/player@0.2.0.[method]player.add-experience-points": async | store | trappable,
        "pumpkin:plugin/player@0.2.0.[method]player.award-advancement": async | store | trappable,
        "pumpkin:plugin/player@0.2.0.[method]player.award-advancement-criterion": async | store | trappable,
        "pumpkin:plugin/player@0.2.0.[method]player.ban": async | store | trappable,
        "pumpkin:plugin/player@0.2.0.[method]player.ban-ip": async | store | trappable,
        "pumpkin:plugin/player@0.2.0.[method]player.damage": async | store | trappable,
        "pumpkin:plugin/player@0.2.0.[method]player.has-permission": async | store | trappable,
        "pumpkin:plugin/player@0.2.0.[method]player.heal": async | store | trappable,
        "pumpkin:plugin/player@0.2.0.[method]player.kill": async | store | trappable,
        "pumpkin:plugin/player@0.2.0.[method]player.open-ender-chest": async | store | trappable,
        "pumpkin:plugin/player@0.2.0.[method]player.open-gui": async | store | trappable,
        "pumpkin:plugin/player@0.2.0.[method]player.respawn": async | store | trappable,
        "pumpkin:plugin/player@0.2.0.[method]player.set-experience-level": async | store | trappable,
        "pumpkin:plugin/player@0.2.0.[method]player.set-experience-points": async | store | trappable,
        "pumpkin:plugin/player@0.2.0.[method]player.set-experience-progress": async | store | trappable,
        "pumpkin:plugin/player@0.2.0.[method]player.set-food-level": async | store | trappable,
        "pumpkin:plugin/player@0.2.0.[method]player.set-gamemode": async | store | trappable,
        "pumpkin:plugin/player@0.2.0.[method]player.set-permission-level": async | store | trappable,
        "pumpkin:plugin/player@0.2.0.[method]player.teleport": async | store | trappable,
        "pumpkin:plugin/player@0.2.0.[method]player.teleport-world": async | store | trappable,
        "pumpkin:plugin/player@0.2.0.[method]java-player.show-dialog": async | store | trappable,
        "pumpkin:plugin/player@0.2.0.[method]java-player.clear-dialog": async | store | trappable,
        "pumpkin:plugin/player@0.2.0.[method]java-player.kick": async | store | trappable,
        "pumpkin:plugin/player@0.2.0.[method]bedrock-player.kick": async | store | trappable,
        "pumpkin:plugin/server@0.2.0.[method]ban-manager.ban-ip": async | store | trappable,
        "pumpkin:plugin/server@0.2.0.[method]ban-manager.ban-player": async | store | trappable,
        "pumpkin:plugin/server@0.2.0.[method]op-manager.deop-player": async | store | trappable,
        "pumpkin:plugin/server@0.2.0.[method]op-manager.op-player": async | store | trappable,
        "pumpkin:plugin/server@0.2.0.[method]server.broadcast": async | store | trappable,
        "pumpkin:plugin/server@0.2.0.[method]server.create-world": async | store | trappable,
        "pumpkin:plugin/server@0.2.0.[method]server.execute-command": async | store | trappable,
        "pumpkin:plugin/server@0.2.0.[method]server.save-all": async | store | trappable,
        "pumpkin:plugin/server@0.2.0.[method]server.unload-world": async | store | trappable,
        "pumpkin:plugin/server@0.2.0.[method]whitelist-manager.set-enabled": async | store | trappable,
        "pumpkin:plugin/world@0.2.0.[method]entity.add-passenger": async | store | trappable,
        "pumpkin:plugin/world@0.2.0.[method]entity.eject-passengers": async | store | trappable,
        "pumpkin:plugin/world@0.2.0.[method]entity.remove-passenger": async | store | trappable,
        "pumpkin:plugin/world@0.2.0.[method]entity.set-swimming": async | store | trappable,
        "pumpkin:plugin/world@0.2.0.[method]entity.set-vehicle": async | store | trappable,
        "pumpkin:plugin/world@0.2.0.[method]entity.teleport": async | store | trappable,
        "pumpkin:plugin/world@0.2.0.[method]living-entity.damage": async | store | trappable,
        "pumpkin:plugin/world@0.2.0.[method]mob.clear-ai-goals": async | store | trappable,
        "pumpkin:plugin/world@0.2.0.[method]world.create-explosion": async | store | trappable,
        "pumpkin:plugin/world@0.2.0.[method]world.save": async | store | trappable,
        "pumpkin:plugin/world@0.2.0.[method]world.set-block": async | store | trappable,
        "pumpkin:plugin/world@0.2.0.[method]world.set-block-by-id": async | store | trappable,
        "pumpkin:plugin/world@0.2.0.[method]world.set-block-by-name": async | store | trappable,
        "pumpkin:plugin/world@0.2.0.[method]world.set-block-state": async | store | trappable,
        "pumpkin:plugin/world@0.2.0.[method]world.set-block-states": async | store | trappable,
        "pumpkin:plugin/world@0.2.0.[method]world.set-raining": async | store | trappable,
        "pumpkin:plugin/world@0.2.0.[method]world.set-thundering": async | store | trappable,
        "pumpkin:plugin/world@0.2.0.[method]world.spawn-entity": async | store | trappable,
        "pumpkin:plugin/world@0.2.0.[method]world.strike-lightning": async | store | trappable,
        "pumpkin:plugin/block-entity@0.2.0.[method]container-block-entity.set-stack": async | trappable,
        "pumpkin:plugin/boss-bar@0.2.0.[drop]boss-bar": async | trappable,
        "pumpkin:plugin/boss-bar@0.2.0.[method]boss-bar.add-player": async | trappable,
        "pumpkin:plugin/boss-bar@0.2.0.[method]boss-bar.get-color": async | trappable,
        "pumpkin:plugin/boss-bar@0.2.0.[method]boss-bar.get-division": async | trappable,
        "pumpkin:plugin/boss-bar@0.2.0.[method]boss-bar.get-health": async | trappable,
        "pumpkin:plugin/boss-bar@0.2.0.[method]boss-bar.get-metadata": async | trappable,
        "pumpkin:plugin/boss-bar@0.2.0.[method]boss-bar.get-players": async | trappable,
        "pumpkin:plugin/boss-bar@0.2.0.[method]boss-bar.get-title": async | trappable,
        "pumpkin:plugin/boss-bar@0.2.0.[method]boss-bar.remove-all": async | trappable,
        "pumpkin:plugin/boss-bar@0.2.0.[method]boss-bar.remove-player": async | trappable,
        "pumpkin:plugin/boss-bar@0.2.0.[method]boss-bar.set-color": async | trappable,
        "pumpkin:plugin/boss-bar@0.2.0.[method]boss-bar.set-division": async | trappable,
        "pumpkin:plugin/boss-bar@0.2.0.[method]boss-bar.set-health": async | trappable,
        "pumpkin:plugin/boss-bar@0.2.0.[method]boss-bar.set-metadata": async | trappable,
        "pumpkin:plugin/boss-bar@0.2.0.[method]boss-bar.set-title": async | trappable,
        "pumpkin:plugin/display@0.2.0.[method]item-display-entity.set-item": async | trappable,
        "pumpkin:plugin/enchantments@0.2.0.[method]enchantment-manager.get-all-enchantment-ids": async | trappable,
        "pumpkin:plugin/enchantments@0.2.0.[method]enchantment-manager.get-enchantment": async | trappable,
        "pumpkin:plugin/enchantments@0.2.0.[method]enchantment-manager.has-enchantment": async | trappable,
        "pumpkin:plugin/enchantments@0.2.0.[method]enchantment-manager.register-enchantment": async | trappable,
        "pumpkin:plugin/gui@0.2.0.[method]gui.clear-items": async | trappable,
        "pumpkin:plugin/gui@0.2.0.[method]gui.get-allow-grab-items": async | trappable,
        "pumpkin:plugin/gui@0.2.0.[method]gui.get-allow-put-items": async | trappable,
        "pumpkin:plugin/gui@0.2.0.[method]gui.get-inventory": async | trappable,
        "pumpkin:plugin/gui@0.2.0.[method]gui.get-item": async | trappable,
        "pumpkin:plugin/gui@0.2.0.[method]gui.get-size": async | trappable,
        "pumpkin:plugin/gui@0.2.0.[method]gui.get-title": async | trappable,
        "pumpkin:plugin/gui@0.2.0.[method]gui.get-type": async | trappable,
        "pumpkin:plugin/gui@0.2.0.[method]gui.set-allow-grab-items": async | trappable,
        "pumpkin:plugin/gui@0.2.0.[method]gui.set-allow-put-items": async | trappable,
        "pumpkin:plugin/gui@0.2.0.[method]gui.set-item": async | trappable,
        "pumpkin:plugin/inventory@0.2.0.[method]inventory.clear": async | trappable,
        "pumpkin:plugin/inventory@0.2.0.[method]inventory.remove-item": async | trappable,
        "pumpkin:plugin/inventory@0.2.0.[method]inventory.set-all-items": async | trappable,
        "pumpkin:plugin/inventory@0.2.0.[method]inventory.set-item": async | trappable,
        "pumpkin:plugin/inventory@0.2.0.[method]player-inventory.clear-all": async | trappable,
        "pumpkin:plugin/inventory@0.2.0.[method]player-inventory.clear-armor": async | trappable,
        "pumpkin:plugin/inventory@0.2.0.[method]player-inventory.clear-main": async | trappable,
        "pumpkin:plugin/inventory@0.2.0.[method]player-inventory.set-boots": async | trappable,
        "pumpkin:plugin/inventory@0.2.0.[method]player-inventory.set-chestplate": async | trappable,
        "pumpkin:plugin/inventory@0.2.0.[method]player-inventory.set-helmet": async | trappable,
        "pumpkin:plugin/inventory@0.2.0.[method]player-inventory.set-item-in-hand": async | trappable,
        "pumpkin:plugin/inventory@0.2.0.[method]player-inventory.set-leggings": async | trappable,
        "pumpkin:plugin/inventory@0.2.0.[method]player-inventory.set-off-hand": async | trappable,
        "pumpkin:plugin/item-stack@0.2.0.[method]item-stack.add-attribute-modifier": async | trappable,
        "pumpkin:plugin/item-stack@0.2.0.[method]item-stack.add-custom-enchantment": async | trappable,
        "pumpkin:plugin/item-stack@0.2.0.[method]item-stack.add-enchantment": async | trappable,
        "pumpkin:plugin/item-stack@0.2.0.[method]item-stack.add-lore": async | trappable,
        "pumpkin:plugin/item-stack@0.2.0.[method]item-stack.clear-attribute-modifiers": async | trappable,
        "pumpkin:plugin/item-stack@0.2.0.[method]item-stack.get-attribute-modifiers": async | trappable,
        "pumpkin:plugin/item-stack@0.2.0.[method]item-stack.get-component-by-id": async | trappable,
        "pumpkin:plugin/item-stack@0.2.0.[method]item-stack.get-components": async | trappable,
        "pumpkin:plugin/item-stack@0.2.0.[method]item-stack.get-count": async | trappable,
        "pumpkin:plugin/item-stack@0.2.0.[method]item-stack.get-custom-data": async | trappable,
        "pumpkin:plugin/item-stack@0.2.0.[method]item-stack.get-custom-enchantment-level": async | trappable,
        "pumpkin:plugin/item-stack@0.2.0.[method]item-stack.get-custom-enchantments": async | trappable,
        "pumpkin:plugin/item-stack@0.2.0.[method]item-stack.get-custom-name": async | trappable,
        "pumpkin:plugin/item-stack@0.2.0.[method]item-stack.get-enchantments": async | trappable,
        "pumpkin:plugin/item-stack@0.2.0.[method]item-stack.get-lore": async | trappable,
        "pumpkin:plugin/item-stack@0.2.0.[method]item-stack.get-max-count": async | trappable,
        "pumpkin:plugin/item-stack@0.2.0.[method]item-stack.get-registry-key": async | trappable,
        "pumpkin:plugin/item-stack@0.2.0.[method]item-stack.get-tags": async | trappable,
        "pumpkin:plugin/item-stack@0.2.0.[method]item-stack.has-custom-data": async | trappable,
        "pumpkin:plugin/item-stack@0.2.0.[method]item-stack.has-custom-enchantment": async | trappable,
        "pumpkin:plugin/item-stack@0.2.0.[method]item-stack.has-tag": async | trappable,
        "pumpkin:plugin/item-stack@0.2.0.[method]item-stack.remove-attribute-modifiers": async | trappable,
        "pumpkin:plugin/item-stack@0.2.0.[method]item-stack.remove-component": async | trappable,
        "pumpkin:plugin/item-stack@0.2.0.[method]item-stack.remove-component-by-id": async | trappable,
        "pumpkin:plugin/item-stack@0.2.0.[method]item-stack.remove-custom-data": async | trappable,
        "pumpkin:plugin/item-stack@0.2.0.[method]item-stack.remove-custom-enchantment": async | trappable,
        "pumpkin:plugin/item-stack@0.2.0.[method]item-stack.remove-enchantment": async | trappable,
        "pumpkin:plugin/item-stack@0.2.0.[method]item-stack.set-component": async | trappable,
        "pumpkin:plugin/item-stack@0.2.0.[method]item-stack.set-component-by-id": async | trappable,
        "pumpkin:plugin/item-stack@0.2.0.[method]item-stack.set-count": async | trappable,
        "pumpkin:plugin/item-stack@0.2.0.[method]item-stack.set-custom-data": async | trappable,
        "pumpkin:plugin/item-stack@0.2.0.[method]item-stack.set-custom-name": async | trappable,
        "pumpkin:plugin/item-stack@0.2.0.[method]item-stack.set-lore": async | trappable,
        "pumpkin:plugin/item-stack@0.2.0.[method]item-stack.to-nbt": async | trappable,
        "pumpkin:plugin/menu@0.2.0.update-slot": async | trappable,
        "pumpkin:plugin/player@0.2.0.[method]bedrock-player.open-form": async | trappable,
        "pumpkin:plugin/player@0.2.0.[method]bedrock-player.send-packet": async | trappable,
        "pumpkin:plugin/player@0.2.0.[method]bedrock-player.send-resource-packs-info": async | trappable,
        "pumpkin:plugin/player@0.2.0.[method]bedrock-player.set-status-flag": async | trappable,
        "pumpkin:plugin/player@0.2.0.[method]java-player.clear-resource-packs": async | trappable,
        "pumpkin:plugin/player@0.2.0.[method]java-player.remove-resource-pack": async | trappable,
        "pumpkin:plugin/player@0.2.0.[method]java-player.send-custom-payload": async | trappable,
        "pumpkin:plugin/player@0.2.0.[method]java-player.send-packet": async | trappable,
        "pumpkin:plugin/player@0.2.0.[method]java-player.send-resource-pack": async | trappable,
        "pumpkin:plugin/player@0.2.0.[method]player.clear-ender-chest": async | trappable,
        "pumpkin:plugin/player@0.2.0.[method]player.delete-message-by-id": async | trappable,
        "pumpkin:plugin/player@0.2.0.[method]player.delete-message-by-signature": async | trappable,
        "pumpkin:plugin/player@0.2.0.[method]player.give-item": async | trappable,
        "pumpkin:plugin/player@0.2.0.[method]player.set-ender-chest-item": async | trappable,
        "pumpkin:plugin/player@0.2.0.[method]player.set-inventory-item": async | trappable,
        "pumpkin:plugin/player@0.2.0.[method]player.set-item-in-hand": async | trappable,
        "pumpkin:plugin/player@0.2.0.[method]player.transfer": async | trappable,
        "pumpkin:plugin/recipe@0.2.0.[method]recipe-manager.match-cooking": async | trappable,
        "pumpkin:plugin/recipe@0.2.0.[method]recipe-manager.match-crafting": async | trappable,
        "pumpkin:plugin/recipe@0.2.0.[method]recipe-manager.register-cooking": async | trappable,
        "pumpkin:plugin/recipe@0.2.0.[method]recipe-manager.register-shaped": async | trappable,
        "pumpkin:plugin/recipe@0.2.0.[method]recipe-manager.register-shapeless": async | trappable,
        "pumpkin:plugin/server@0.2.0.[method]server.get-all-enchantment-ids": async | trappable,
        "pumpkin:plugin/server@0.2.0.[method]server.get-enchantment": async | trappable,
        "pumpkin:plugin/world@0.2.0.[method]entity.set-item-stack": async | trappable,
        "pumpkin:plugin/world@0.2.0.[method]living-entity.set-equipment": async | trappable,
        "pumpkin:plugin/world@0.2.0.[method]world.drop-item": async | trappable,
        "pumpkin:plugin/world@0.2.0.[method]world.set-item-storage": async | trappable,
        default: trappable,
    },
    exports: { default: async | store | trappable },
});
