package pumpkin:plugin@0.1.0;

interface attributes {
  enum attribute {
    generic.armor,
    generic.armor-toughness,
    generic.attack-damage,
    generic.attack-knockback,
    generic.attack-speed,
    player.block-break-speed,
    player.block-interaction-range,
    generic.burning-time,
    generic.explosion-knockback-resistance,
    player.entity-interaction-range,
    generic.fall-damage-multiplier,
    generic.flying-speed,
    generic.follow-range,
    generic.gravity,
    generic.jump-strength,
    generic.knockback-resistance,
    generic.luck,
    generic.max-absorption,
    generic.max-health,
    player.mining-efficiency,
    generic.movement-efficiency,
    generic.movement-speed,
    generic.oxygen-bonus,
    generic.safe-fall-distance,
    generic.scale,
    player.sneaking-speed,
    zombie.spawn-reinforcements,
    generic.step-height,
    player.submerged-mining-speed,
    player.sweeping-damage-ratio,
    generic.water-movement-efficiency,
  }
  enum modifier-operation {
    add,
    multiply-base,
    multiply-total,
  }
  record attribute-modifier {
    id: string,
    amount: f64,
    operation: modifier-operation,
  }
}
