package pumpkin:plugin@0.1.0;

interface data-components {
  enum data-component {
    custom-data,
    max-stack-size,
    max-damage,
    damage,
    unbreakable,
    custom-name,
    item-name,
    lore,
    rarity,
    enchantments,
    can-place-on,
    can-break,
    attribute-modifiers,
    custom-model-data,
    hide-additional-tooltip,
    hide-tooltip,
    repair-cost,
    creative-slot-lock,
    enchantment-glint-override,
    intangible-projectile,
    food,
    fire-resistant,
    tool,
    stored-enchantments,
    dyed-color,
    map-color,
    map-id,
    map-decorations,
    map-post-processing,
    charged-projectiles,
    bundle-contents,
    potion-contents,
    suspicious-stew-effects,
    writable-book-content,
    written-book-content,
    trim,
    debug-stick-state,
    entity-data,
    bucket-entity-data,
    block-entity-data,
    instrument,
    ominous-bottle-amplifier,
    jukebox-playable,
    recipes,
    lodestone-tracker,
    firework-explosion,
    fireworks,
    profile,
    note-block-sound,
    banner-patterns,
    base-color,
    pot-decorations,
    container,
    block-state,
    bees,
    lock,
    container-loot,
  }
}
