package pumpkin:plugin@0.1.0;

interface entity-types {
  enum entity-type {
    allay,
    area-effect-cloud,
    armadillo,
    armor-stand,
    arrow,
    axolotl,
    bat,
    bee,
    blaze,
    block-display,
    boat,
    bogged,
    breeze,
    breeze-wind-charge,
    camel,
    cat,
    cave-spider,
    chest-boat,
    chest-minecart,
    chicken,
    cod,
    command-block-minecart,
    cow,
    creeper,
    dolphin,
    donkey,
    dragon-fireball,
    drowned,
    egg,
    elder-guardian,
    end-crystal,
    ender-dragon,
    ender-pearl,
    enderman,
    endermite,
    evoker,
    evoker-fangs,
    experience-bottle,
    experience-orb,
    eye-of-ender,
    falling-block,
    fireball,
    firework-rocket,
    fishing-bobber,
    fox,
    frog,
    furnace-minecart,
    ghast,
    giant,
    glow-item-frame,
    glow-squid,
    goat,
    guardian,
    hoglin,
    hopper-minecart,
    horse,
    husk,
    illusioner,
    interaction,
    iron-golem,
    item,
    item-display,
    item-frame,
    leash-knot,
    lightning-bolt,
    llama,
    llama-spit,
    magma-cube,
    marker,
    minecart,
    mooshroom,
    mule,
    ocelot,
    ominous-item-spawner,
    painting,
    panda,
    parrot,
    phantom,
    pig,
    piglin,
    piglin-brute,
    pillager,
    player,
    polar-bear,
    potion,
    pufferfish,
    rabbit,
    ravager,
    salmon,
    sheep,
    shulker,
    shulker-bullet,
    silverfish,
    skeleton,
    skeleton-horse,
    slime,
    small-fireball,
    sniffer,
    snow-golem,
    snowball,
    spawner-minecart,
    spectral-arrow,
    spider,
    squid,
    stray,
    strider,
    tadpole,
    text-display,
    tnt,
    tnt-minecart,
    trader-llama,
    trident,
    tropical-fish,
    turtle,
    vex,
    villager,
    vindicator,
    wandering-trader,
    warden,
    wind-charge,
    witch,
    wither,
    wither-skeleton,
    wither-skull,
    wolf,
    zoglin,
    zombie,
    zombie-horse,
    zombie-villager,
    zombified-piglin,
  }
}
