package pumpkin:plugin@0.1.0;

interface game-rules {
  enum game-rule {
    announce-advancements,
    block-explosion-drop-decay,
    command-block-output,
    command-modification-block-limit,
    disable-elytra-movement-check,
    disable-raids,
    do-daylight-cycle,
    do-entity-drops,
    do-fire-tick,
    do-immediate-respawn,
    do-insomnia,
    do-limited-crafting,
    do-mob-loot,
    do-mob-spawning,
    do-patrol-spawning,
    do-tile-drops,
    do-trader-spawning,
    do-vines-spread,
    do-warden-spawning,
    do-weather-cycle,
    drowning-damage,
    ender-pearls-vanish-on-death,
    fall-damage,
    fire-damage,
    forgive-dead-players,
    freeze-damage,
    global-sound-events,
    keep-inventory,
    lava-source-conversion,
    log-admin-commands,
    max-command-chain-length,
    max-command-fork-count,
    max-entity-cramming,
    mob-explosion-drop-decay,
    mob-griefing,
    natural-regeneration,
    players-nether-portal-creative-delay,
    players-nether-portal-default-delay,
    players-sleeping-percentage,
    projectiles-can-break-blocks,
    random-tick-speed,
    reduced-debug-info,
    send-command-feedback,
    show-death-messages,
    snow-accumulation-height,
    spawn-chunk-radius,
    spawn-radius,
    spectators-generate-chunks,
    tnt-explosion-drop-decay,
    universal-anger,
    water-source-conversion,
  }
  variant game-rule-value {
    int(s32),
    %bool(bool),
  }
}
