package pumpkin:plugin@0.1.0;

interface game-rules {
  enum game-rule {
    announceAdvancements,
    blockExplosionDropDecay,
    commandBlockOutput,
    commandModificationBlockLimit,
    disableElytraMovementCheck,
    disableRaids,
    doDaylightCycle,
    doEntityDrops,
    doFireTick,
    doImmediateRespawn,
    doInsomnia,
    doLimitedCrafting,
    doMobLoot,
    doMobSpawning,
    doPatrolSpawning,
    doTileDrops,
    doTraderSpawning,
    doVinesSpread,
    doWardenSpawning,
    doWeatherCycle,
    drowningDamage,
    enderPearlsVanishOnDeath,
    fallDamage,
    fireDamage,
    forgiveDeadPlayers,
    freezeDamage,
    globalSoundEvents,
    keepInventory,
    lavaSourceConversion,
    logAdminCommands,
    maxCommandChainLength,
    maxCommandForkCount,
    maxEntityCramming,
    mobExplosionDropDecay,
    mobGriefing,
    naturalRegeneration,
    playersNetherPortalCreativeDelay,
    playersNetherPortalDefaultDelay,
    playersSleepingPercentage,
    projectilesCanBreakBlocks,
    randomTickSpeed,
    reducedDebugInfo,
    sendCommandFeedback,
    showDeathMessages,
    snowAccumulationHeight,
    spawnChunkRadius,
    spawnRadius,
    spectatorsGenerateChunks,
    tntExplosionDropDecay,
    universalAnger,
    waterSourceConversion,
  }
  variant game-rule-value {
    int(s32),
    %bool(bool),
  }
}
